# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['main.py'],
    pathex=['src'],
    binaries=[],
    datas=[('config.json', '.')],
    hiddenimports=[
        'koudouhyo',
        'koudouhyo.models',
        'koudouhyo.database',
        'koudouhyo.repositories',
        'koudouhyo.exceptions',
        'koudouhyo.services',
        'koudouhyo.services.config_loader',
        'koudouhyo.services.user_context',
        'koudouhyo.services.lock_manager',
        'koudouhyo.services.backup_manager',
        'koudouhyo.services.version_checker',
        'koudouhyo.services.migration_manager',
        'koudouhyo.services.status_service',
        'koudouhyo.services.admin_service',
        'koudouhyo.ui',
        'koudouhyo.ui.main_window',
        'koudouhyo.ui.edit_window',
        'koudouhyo.ui.admin_window',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Koudouhyo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
